# Generated by Django 2.0.13 on 2019-04-09 00:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 0, 17, 10, 570417, tzinfo=utc)),
        ),
    ]
